[build]
dockerfile = "Dockerfile"
buildCommand = "docker build --no-cache -t onta:latest ."

[variables]
DB_HOST = ""
DB_USER = ""
DB_PASS = ""
DB_NAME = ""
QR_SECRET = ""
APP_ENV = "production"
APP_URL = ""
SITENAME = "ONTA Asistencia QR"
RECAPTCHA_SITE_KEY = ""
RECAPTCHA_SECRET_KEY = ""
